import Foundation

/// Generated by release CI. Do not edit in a release checkout.
enum GeneratedReleaseMetadata {
    static let familyBaseVersion = "3.3.0"
    static let releaseIdentity = "3.3.0-dev.561"
    static let releaseSetId = "mentra-3.3.0-dev.561"
    static let sourceCommit = "802489a5d175352a3b27e7e0b628875ccc943117"
    static let otaManifestUrl = "https://artifactscdn.mentraglass.com/Mentra-Community/MentraOS/releases/mentra-builds-v3.3.0/mentra-live-ota-3.3.0-dev.561.json"
    static let otaManifestSha256 = "a3ba40997d9722d5d2ba2439f7329df3cd032230ea4a042cc164c2d82c578f00"
}
