import Foundation

/// Generated by release CI. Do not edit in a release checkout.
enum GeneratedReleaseMetadata {
    static let familyBaseVersion = "3.2.1"
    static let releaseIdentity = "3.2.1-dev.307"
    static let releaseSetId = "mentra-3.2.1-dev.307"
    static let sourceCommit = "47af5182ab2b24ec2df7ede43ebaa5fc35be31d0"
    static let otaManifestUrl = "https://artifactscdn.mentraglass.com/Mentra-Community/MentraOS/releases/mentra-builds-v3.2.1/mentra-live-ota-3.2.1-dev.307.json"
    static let otaManifestSha256 = "130bfa43a8dd96915f039cefcc843b90ecfabec911c4a98a097cd8be8b152a92"
}
