import Foundation

/// Generated by release CI. Do not edit in a release checkout.
enum GeneratedReleaseMetadata {
    static let familyBaseVersion = "3.1.0"
    static let releaseIdentity = "3.1.0-dev.51"
    static let releaseSetId = "mentra-3.1.0-dev.51"
    static let sourceCommit = "f991a69af06ba9498b1da5b23034a5ff67558b08"
    static let otaManifestUrl = "https://github.com/Mentra-Community/MentraOS/releases/download/mentra-builds-v3.1.0/mentra-live-ota-3.1.0-dev.51.json"
    static let otaManifestSha256 = "b9e5a6fa7bf65b0d19b45691f6dd7c335a4c6e4d66ec136049294e9cc6bb3a48"
}
